lab1
Katerinka12125/networks pull request #1
Opened 2020-09-18 05:10 UTC by Katerinka12125

@Aloomenon

2020-09-20 13:46 UTC, Aloomenon requested changes
Расскажите, что такое сокет и как это работает.

2020-09-22 06:49 UTC, Katerinka12125 commented
@Aloomenon 1. Программа в цикле отправляет сообщение о своём присутствии в сети и получает сообщения всех участников мультикаст группы (своё сообщение в том числе), все это происходит с каким-то интервалом.  У нас есть тайм-аут на получение пакетов, чтобы получать пакеты пока они приходят, но если пакетов нет, то переходим в сенд. Программа считается отключённой, если прошло какое-то время с момента последнего сообщения от неё. 
 2. Сокет-точка, через которую происходит соединение, связка айпи+порт. Через его Каналы ввода/вывода общаются клиент с сервером. У нас есть datagramSocket (отвечает за рассылку) , multicastSocket ( в multicastSocket мы слушаем группу людей, которую подключена к определённому Ip-адресу). Мультикаст сокет биндим на определённый порт, чтобы знать, на какой порт потом отправлять датаграмму. Грубо говоря, маршрутизатор запоминает то, что мы слушаем, и потом мы отправляем datagram пакеты с datagramsocket (пакеты, которые должна группа получить), те мы создали datagramsocket, а через него посылаем datagram пакеты (письма, в которых мы прикрепляем сообщение какое-то и айпи адрес, к которому мы подключаем группу, и порт).

2020-09-22 06:50 UTC, Katerinka12125 commented
@Aloomenon поправила код, добавила закрытие сокетов через try-with-resources

2020-09-24 14:34 UTC, Aloomenon commented
ок. принял. Имя и фамилию напишите.

2020-09-24 15:27 UTC, Katerinka12125 commented
@Aloomenon Корчашкина Катя, группа 18204

2020-10-03 09:10 UTC, merged